apiVersion: v1
kind: Service
metadata:
  name: smb-mengxin-pink-clusterip
  namespace: tcp
  labels:
    app: smb-mengxin-pink
spec:
  selector:
    pod: smb-mengxin-pink
  type: ClusterIP
  ports:
    - name: smb-445
      port: 445
      targetPort: 445
