apiVersion: v1
kind: Service
metadata:
  name: httpbin-mengxin-pink-clusterip
  namespace: web
  labels:
    app: httpbin-mengxin-pink
spec:
  selector:
    pod: httpbin-mengxin-pink
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80