apiVersion: apps/v1
kind: Deployment
metadata:
  name: sea-mengxin-pink-deployment
  namespace: web
  labels:
    app: sea
    hostname: sea.mengxin.pink
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: sea-mengxin-pink
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        pod: sea-mengxin-pink
    spec:
      containers:
        - name: sea-mengxin-pink
          image: mengxin891029/sea-mengxin-pink
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          securityContext:
            allowPrivilegeEscalation: false
            # runAsNonRoot: true
            # readOnlyRootFilesystem: true