apiVersion: v1
kind: Service
metadata:
  name: chat-mengxin-pink-clusterip
  namespace: web
  labels:
    app: chat-mengxin-pink
spec:
  selector:
    pod: chat-mengxin-pink
  type: ClusterIP
  ports:
    - name: chat-http
      port: 3000
      targetPort: 3000
