apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-storage-pv
  namespace: web
spec:
  storageClassName: pihole-storage
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: web
    name: pihole-storage-pvc
  nfs:
    path: /storage/pihole
    server: 10.1.0.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-storage-pvc
  namespace: web
spec:
  storageClassName: pihole-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G

