apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tunnel-mengxin-pink-daemonset
  namespace: web
  labels:
    app: tunnel
spec:
  selector:
    matchLabels:
      pod: tunnel-mengxin-pink
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        pod: tunnel-mengxin-pink
    spec:
      containers:
        - name: tunnel-mengxin-pink
          image: erisamoe/cloudflared:latest
          volumeMounts:
          - name: tunnel-mengxin-pink-configmap-volume
            mountPath: /etc/cloudflared
          command: [ "/cloudflared", "tunnel","--no-autoupdate", "run" ]
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: tunnel-mengxin-pink-configmap-volume
          configMap:
            name: tunnel-mengxin-pink-configmap
      # restartPolicy: Never

