apiVersion: apps/v1
kind: Deployment
metadata:
  name: tunnel-mengxin-pink-deployment
  namespace: web
  labels:
    app: tunnel
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: tunnel-mengxin-pink
  template:
    metadata:
      labels:
        pod: tunnel-mengxin-pink
    spec:
      containers:
        - name: tunnel-mengxin-pink
          image: erisamoe/cloudflared
          volumeMounts:
          - name: tunnel-mengxin-pink-configmap-volume
            mountPath: /etc/cloudflared
          command: [ "/cloudflared", "tunnel", "run" ]
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: tunnel-mengxin-pink-configmap-volume
          configMap:
            name: tunnel-mengxin-pink-configmap
      # restartPolicy: Never

