apiVersion: apps/v1
kind: Deployment
metadata:
    name: grpc-mengxin-pink-deployment
    namespace: web
    labels:
        app: grpc
        hostname: grpc.mengxin.pink
spec:
    replicas: 1
    selector:
        matchLabels:
            pod: grpc-mengxin-pink
    template:
        metadata:
            # annotations:
            #     linkerd.io/inject: enabled
            labels:
                pod: grpc-mengxin-pink
        spec:
            containers:
                - name: grpc-mengxin-pink
                  image: mengxin891029/grpc-mengxin-pink
                  imagePullPolicy: Always
                  ports:
                      - name: grpc
                        containerPort: 50051
                  securityContext:
                        allowPrivilegeEscalation: false
                        # runAsNonRoot: true
                        readOnlyRootFilesystem: true
            
