apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-storage-pv
  namespace: tcp
spec:
  storageClassName: postgres-storage
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: tcp
    name: postgres-storage-pvc
  nfs:
    path: /storage/postgres
    server: 10.1.0.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-storage-pvc
  namespace: tcp
spec:
  storageClassName: postgres-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G

