apiVersion: v1
kind: Service
metadata:
  name: postgres-mengxin-pink-clusterip
  namespace: tcp
  labels:
    app: postgres-mengxin-pink
spec:
  selector:
    pod: postgres-mengxin-pink
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
