apiVersion: v1
kind: Service
metadata:
  name: sea-mengxin-pink-clusterip
  namespace: web
  labels:
    app: sea-mengxin-pink
spec:
  selector:
    pod: sea-mengxin-pink
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80