apiVersion: apps/v1
kind: Deployment
metadata:
  name: sea-mengxin-ml-deployment
  namespace: web
  labels:
    app: sea
    hostname: sea.mengxin.ml
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: sea-mengxin-ml
  template:
    metadata:
      labels:
        pod: sea-mengxin-ml
    spec:
      containers:
        - name: sea-mengxin-ml
          image: mengxin891029/sea-mengxin-ml
          ports:
            - name: http
              containerPort: 80
