apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-mengxin-pink-deployment
  namespace: web
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: mongo-express-mengxin-pink
  template:
    metadata:
      labels:
        pod: mongo-express-mengxin-pink
    spec:
      containers:
        - name: mongo-mengxin-pink
          image: mongo-express
          ports:
            - containerPort: 8081
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-express-mengxin-pink-config
                  key: ME_CONFIG_MONGODB_ADMINUSERNAME
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-express-mengxin-pink-config
                  key: ME_CONFIG_MONGODB_ADMINPASSWORD
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                secretKeyRef:
                  name: mongo-express-mengxin-pink-config
                  key: ME_CONFIG_MONGODB_SERVER
